# Utilisez l'image officielle Maven comme base
FROM maven:3.8-jdk-11

# Définissez le répertoire de travail dans le conteneur
WORKDIR /app

# Copiez le fichier pom.xml pour installer les dépendances
COPY pom.xml .

# Copiez tout le code source dans le conteneur
COPY src ./src

# Exécutez Maven pour compiler le projet et générer le fichier WAR
CMD ["mvn", "clean", "package"]

# Lorsque la compilation est terminée, le fichier WAR sera généré dans le répertoire target
