# Utilisez une image de base Tomcat
FROM tomcat:10.1.15-jdk11-temurin-jammy

# Copiez votre application WAR (Web Archive) dans le répertoire webapps de Tomcat
COPY ./target/*.war /usr/local/tomcat/webapps

# Exposez le port sur lequel Tomcat écoute (par défaut 8080)
EXPOSE 8081
